name: CI
on:
  push:
    branches:
      - "**"
  
env:
  NODE_VERSION: 22.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "${{ env.NODE_VERSION }}"
          cache: "pnpm"
          
      - run: pnpm install --frozen-lockfile
      - run: pnpm run all
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
